FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    git curl build-essential libssl-dev zlib1g-dev \
    && git clone https://github.com/TelegramMessenger/MTProxy.git /opt/mtproxy \
    && cd /opt/mtproxy && make \
    && apt-get clean

WORKDIR /opt/mtproxy

RUN curl -s https://core.telegram.org/getProxyConfig -o proxy-multi.conf && \
    curl -s https://core.telegram.org/getProxySecret -o proxy-secret

EXPOSE 443

CMD curl -s https://core.telegram.org/getProxyConfig -o proxy-multi.conf && \
    curl -s https://core.telegram.org/getProxySecret -o proxy-secret && \
    ./objs/bin/mtproto-proxy -u nobody -p 8888 -H 443 \
    -S ${SECRET} \
    --aes-pwd proxy-secret proxy-multi.conf \
    -M 2