services:
  mtproto:
    image: telegrammessenger/proxy:latest
    container_name: mtproto
    restart: always
    ports:
      - "443:443"
    env_file:
      - .env

  xray:
    image: teddysun/xray
    container_name: xray
    restart: always
    ports:
      - "8443:443"
    env_file:
      - .env
    volumes:
      - .:/data
    entrypoint: ["sh", "-c"]
    command:
      - |
        chmod 644 /data/xray-config.json.template
        sed -e "s|XRAY_UUID_PLACEHOLDER|$XRAY_UUID|g" -e "s|XRAY_SERVER_NAME_PLACEHOLDER|$XRAY_SERVER_NAME|g" -e "s|XRAY_PRIVATE_KEY_PLACEHOLDER|$XRAY_PRIVATE_KEY|g" -e "s|XRAY_SHORT_ID_PLACEHOLDER|$XRAY_SHORT_ID|g" /data/xray-config.json.template > /etc/xray/config.json
        xray run -config /etc/xray/config.json 